name: Build Windows App

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Windows Release Build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: '3.32.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows

      - name: Show contents of build folder (debug)
        run: dir build\windows\runner\Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/runner/Release
