name: Build Windows App

on:
  push:
    branches: [ master ] # yoki master agar sizda shunday bo‘lsa

jobs:
  build:
    name: Windows Release Build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/runner/Release
